name: all-the-things
on: push
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: docker run --rm -i hadolint/hadolint:latest-alpine hadolint --ignore SC1091 --ignore DL3008 - < Dockerfile
  deploy:
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: set env variables
        env:
          IMAGE_NAME: quay.io/dyco/dyco-mirror
        run: |
          GIT_SHORT_SHA=${GITHUB_SHA:0:8}
          echo "image_tags=${IMAGE_NAME}:${GIT_SHORT_SHA},${IMAGE_NAME}:latest" >> ${GITHUB_ENV}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.image_tags }}
